version: '3.8'

services:
  app:
    container_name: password_manager_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: password_manager_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password_manager
    ports:
      - "5432:5432"
